# Generated by Django 3.2.4 on 2021-07-10 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('first_login_date', models.DateTimeField()),
                ('setup_confirmed', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SunsetRatingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Date and Time of Recording')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sunsetRatingReciever.user')),
            ],
        ),
    ]
