# Generated by Django 3.2.4 on 2021-07-10 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sunsetRatingReciever', '0002_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sunsetratingentry',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to='sunsetRatingReciever.user'),
        ),
    ]
