# Generated by Django 3.2.4 on 2021-07-18 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunsetRatingReciever', '0003_alter_sunsetratingentry_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secret_key',
            field=models.CharField(default='abc', max_length=20),
            preserve_default=False,
        ),
    ]
