# Generated by Django 3.2.4 on 2021-08-01 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunsetRatingReciever', '0004_user_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='sunsetratingentry',
            name='air_quality_index',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='sunsetratingentry',
            name='cloud_cover_percent',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='sunsetratingentry',
            name='humidity',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='sunsetratingentry',
            name='minutes_to_sunset',
            field=models.DecimalField(decimal_places=1, default=None, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='sunsetratingentry',
            name='season',
            field=models.CharField(default=None, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='sunsetratingentry',
            name='sunset_time',
            field=models.DateTimeField(default=None, null=True, verbose_name='Date and Time of Sunset'),
        ),
        migrations.AddField(
            model_name='sunsetratingentry',
            name='temperature',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='sunsetratingentry',
            name='time_from_last_rain_to_sunset',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True),
        ),
    ]
