# Generated by Django 3.2.4 on 2021-08-28 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunsetRatingReciever', '0007_sunsetratingentry_air_pressure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sunsetratingentry',
            name='air_pressure',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sunsetratingentry',
            name='air_quality_index',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sunsetratingentry',
            name='cloud_cover_percent',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sunsetratingentry',
            name='humidity',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sunsetratingentry',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='sunsetratingentry',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='sunsetratingentry',
            name='minutes_to_sunset',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='sunsetratingentry',
            name='season',
            field=models.CharField(blank=True, default=None, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='sunsetratingentry',
            name='sunset_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Date and Time of Sunset'),
        ),
        migrations.AlterField(
            model_name='sunsetratingentry',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='sunsetratingentry',
            name='time_from_last_rain_to_sunset',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
    ]
