# Generated by Django 3.2.4 on 2021-08-29 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunsetRatingReciever', '0008_auto_20210827_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='sunsetratingentry',
            name='air_quality_pm10',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
