# Generated by Django 3.2.4 on 2021-08-29 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunsetRatingReciever', '0009_sunsetratingentry_air_quality_pm10'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sunsetratingentry',
            name='air_quality_pm10',
            field=models.DecimalField(blank=True, decimal_places=10, default=None, max_digits=15, null=True),
        ),
    ]
